/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_relinc_libraries_staticClasses_KftKasierFilter */

#ifndef _Included_net_relinc_libraries_staticClasses_KftKasierFilter
#define _Included_net_relinc_libraries_staticClasses_KftKasierFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_relinc_libraries_staticClasses_KftKasierFilter
 * Method:    lowPassFilter
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_relinc_libraries_staticClasses_KftKasierFilter_lowPassFilter
  (JNIEnv *, jobject, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
